---
- name: Declaring the variables in the beginning 
  hosts: all
  vars:
    usr:
    - tom
    - sawyer
    - harry
    - mike
    - jakson
  tasks:
  - name: create multiple user
    user:
      name: "{{ item }}"
      state: present
    loop: "{{ usr }}"
