---
- name: Experimenting the variable in the same playbook
  hosts: all
  vars:
    pkg: httpd
    usr: peter
  tasks:
  - name: Install a Package {{ pkg }} of httpd
    yum:
      name: "{{ pkg }}"
      state: present

  - name: Create a webpage
    copy: 
      content: "Hi Today we are learninnnnnng the variable additions in the ansible playbook"
      dest: /var/www/html/index.html

  - name: Start the service with the package {{ pkg }}
    service:
      name: "{{ pkg }}"
      state: started
      enabled: true

  - name: Add a User {{ usr }}
    user:
      name: "{{ usr }}"
      uid: 30002
      state: present       





 
